---
mysql:
  host: localhost
  user: user
  password: password
  db: db
vk:
  login: +79112223344
  password: password
country_ids:
  # These are CIS countries ++ post USSR
  # Страны СНГ ++ пост СССР
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18